import type {
  Address,
  Category,
  DeliveryContact,
  DeliveryOrder,
  Food,
  NotificationItem,
  Order,
  UserProfile,
} from "@/api/types";

export const heroStats = [
  { label: "Orders delivered today", value: "1,248" },
  { label: "Average prep time", value: "18 mins" },
  { label: "Top rated dishes", value: "42" },
];

export const promoCards = [
  {
    title: "Signature Flame Grills",
    copy: "Fresh off the fire with chef-crafted spice balance and silky sides.",
  },
  {
    title: "Delivery Within Lagos",
    copy: "Order for delivery, pickup, or dine-in across Lagos.",
  },
];

export const demoCategories: Category[] = [
  { id: "1", name: "Atrium Menu", slug: "atrium-menu", description: "Main restaurant menu", sort_order: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "2", name: "Indian Food", slug: "indian-food", description: "Indian food menu", sort_order: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export const demoFoods: Food[] = [
  {
    id: "101",
    category_id: "1",
    name: "Jollof Rice & Chicken",
    slug: "jollof-rice-chicken",
    description: "A portion of jollof rice served with chicken thigh or drumstick and vegetables.",
    price: 3800,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "102",
    category_id: "1",
    name: "Fried Rice & Chicken",
    slug: "fried-rice-chicken",
    description: "A portion of fried rice served with chicken thigh or drumstick and vegetables.",
    price: 3800,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "103",
    category_id: "1",
    name: "White Rice with Chicken Stew",
    slug: "white-rice-with-chicken-stew",
    description: "White rice served with chicken stew.",
    price: 3800,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "104",
    category_id: "1",
    name: "Asun Jollof Rice & Chicken",
    slug: "asun-jollof-rice-chicken",
    description: "Jollof rice mixed with asun goat meat and served with chicken.",
    price: 7000,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 24,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "105",
    category_id: "1",
    name: "Asun Fried Rice & Chicken",
    slug: "asun-fried-rice-chicken",
    description: "Fried rice mixed with asun goat meat and served with chicken.",
    price: 7000,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 24,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "106",
    category_id: "1",
    name: "Catfish Pepper Soup with Yam",
    slug: "catfish-pepper-soup-with-yam",
    description: "Catfish pepper soup served with yam.",
    price: 4300,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "107",
    category_id: "1",
    name: "Goat Meat Pepper Soup with Yam",
    slug: "goat-meat-pepper-soup-with-yam",
    description: "Goat meat pepper soup served with yam.",
    price: 4300,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "108",
    category_id: "1",
    name: "Boiled Yam & Egg Sauce",
    slug: "boiled-yam-egg-sauce",
    description: "Boiled yam served with egg sauce.",
    price: 2700,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "109",
    category_id: "1",
    name: "Fried Yam & Egg Sauce",
    slug: "fried-yam-egg-sauce",
    description: "Fried yam served with egg sauce.",
    price: 2700,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "110",
    category_id: "1",
    name: "Chicken Shawarma",
    slug: "chicken-shawarma",
    description: null,
    price: 4900,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "111",
    category_id: "1",
    name: "Chicken Shawarma Sausage",
    slug: "chicken-shawarma-sausage",
    description: null,
    price: 6000,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "112",
    category_id: "1",
    name: "Indomie Veg",
    slug: "indomie-veg",
    description: null,
    price: 3800,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "113",
    category_id: "1",
    name: "Indomie Chicken",
    slug: "indomie-chicken",
    description: null,
    price: 4900,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "114",
    category_id: "1",
    name: "Indomie Chicken & Sausage",
    slug: "indomie-chicken-sausage",
    description: null,
    price: 6000,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "115",
    category_id: "1",
    name: "Indomie Chicken & Egg",
    slug: "indomie-chicken-egg",
    description: null,
    price: 6000,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "116",
    category_id: "1",
    name: "Chicken & Chips (Chicken Thigh or Drumstick)",
    slug: "chicken-chips-chicken-thigh-or-drumstick",
    description: null,
    price: 4400,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "117",
    category_id: "1",
    name: "Chicken & Chips (Chicken Lap)",
    slug: "chicken-chips-chicken-lap",
    description: null,
    price: 7200,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "118",
    category_id: "2",
    name: "Onion Cake",
    slug: "onion-cake",
    description: null,
    price: 1500,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "119",
    category_id: "2",
    name: "Chicken Buns",
    slug: "chicken-buns",
    description: null,
    price: 1500,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "120",
    category_id: "2",
    name: "Punjabi Samosa",
    slug: "punjabi-samosa",
    description: null,
    price: 1500,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "121",
    category_id: "2",
    name: "Vegetable Spring Rolls",
    slug: "vegetable-spring-rolls",
    description: null,
    price: 600,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "122",
    category_id: "2",
    name: "Vegetable Samosa",
    slug: "vegetable-samosa",
    description: null,
    price: 600,
    image_url: null,
    image_path: null,
    is_available: true,
    preparation_time_minutes: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoOrders: Order[] = [
  {
    id: "ord-1",
    user_id: "user-1",
    order_number: "BM12456789",
    order_type: "DELIVERY",
    delivery_address_id: "addr-1",
    status: "OUT_FOR_DELIVERY",
    subtotal: 13600,
    delivery_fee: 1500,
    delivery_distance_km: 6.4,
    total: 15100,
    notes: "Please call on arrival.",
    table_number: null,
    scheduled_pickup_time: null,
    payment_status: "SUCCESSFUL",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "oi-1", food_item_id: "101", food_name_snapshot: "Jollof Rice & Chicken", quantity: 1, unit_price: 3800, subtotal: 3800 },
      { id: "oi-2", food_item_id: "110", food_name_snapshot: "Chicken Shawarma", quantity: 2, unit_price: 4900, subtotal: 9800 },
    ],
  },
];

export const demoAddresses: Address[] = [
  {
    id: "addr-1",
    user_id: "user-1",
    label: "Home",
    address: "12 Admiralty Way",
    city: "Lekki",
    state: "Lagos",
    phone: "+2348012345678",
    latitude: null,
    longitude: null,
    is_default: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoNotifications: NotificationItem[] = [
  {
    id: "not-1",
    user_id: "user-1",
    title: "Order on the way",
    message: "Your rider has picked up BM12456789 and is heading to your address.",
    type: "DELIVERY",
    is_read: false,
    deliveries: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoProfile: UserProfile = {
  id: "user-1",
  role_id: "role-customer",
  first_name: "Amara",
  last_name: "Okafor",
  email: "amara@example.com",
  phone: "+2348012345678",
  is_verified: true,
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const demoDeliveryOrders: DeliveryOrder[] = [
  {
    id: "delivery-1",
    order_id: "ord-1",
    delivery_personnel_id: "rider-1",
    delivery_address_id: "addr-1",
    status: "ASSIGNED",
    estimated_delivery_time: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    picked_up_at: null,
    delivered_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoDeliveryContact: DeliveryContact = {
  order_id: "ord-1",
  customer_name: "Amara Okafor",
  customer_phone: "+2348012345678",
  delivery_address: "12 Admiralty Way",
  city: "Lekki",
  state: "Lagos",
};
